[package]
name = "server"
version = "0.1.0"
edition = "2021"

[dependencies]
serde    = { version = "1.0.210", features = ["derive"] }
tokio    = { version = "1", features = ["full"] }
axum     = "0.7.5"
sailfish = "0.8.3"
config   = { path = "../common/lib/config" }
